const { default: makeWASocket, useMultiFileAuthState, DisconnectReason, jidDecode } = require('@whiskeysockets/baileys');
const pino = require('pino');
const fs = require('fs');
const path = require('path');
const { connectDB, User } = require('./database');
const config = require('./config');

connectDB();

// Load Session from String (for Cloud)
if (config.sessionID && config.sessionID.startsWith('ULTRA~')) {
    if (!fs.existsSync('./auth_info')) fs.mkdirSync('./auth_info');
        const creds = Buffer.from(config.sessionID.replace('ULTRA~', ''), 'base64');
            fs.writeFileSync('./auth_info/creds.json', creds);
            }

            async function startBot() {
                const { state, saveCreds } = await useMultiFileAuthState('./auth_info');
                    const sock = makeWASocket({
                            logger: pino({ level: 'silent' }),
                                    printQRInTerminal: true,
                                            auth: state,
                                                    browser: [config.botName, "Chrome", "1.0"]
                                                        });

                                                            sock.ev.on('creds.update', saveCreds);

                                                                sock.ev.on('connection.update', (update) => {
                                                                        const { connection, lastDisconnect } = update;
                                                                                if (connection === 'close') {
                                                                                            const shouldReconnect = (lastDisconnect.error)?.output?.statusCode !== DisconnectReason.loggedOut;
                                                                                                        if (shouldReconnect) startBot();
                                                                                                                } else if (connection === 'open') {
                                                                                                                            console.log(`🚀 ${config.botName} IS ONLINE!`);
                                                                                                                                    }
                                                                                                                                        });

                                                                                                                                            sock.ev.on('messages.upsert', async (m) => {
                                                                                                                                                    const msg = m.messages[0];
                                                                                                                                                            if (!msg.message || msg.key.fromMe) return;

                                                                                                                                                                    const sender = msg.key.remoteJid;
                                                                                                                                                                            const text = msg.message.conversation || msg.message.extendedTextMessage?.text || "";
                                                                                                                                                                                    
                                                                                                                                                                                            // 1. DATABASE CHECK
                                                                                                                                                                                                    let user = await User.findOne({ id: sender });
                                                                                                                                                                                                            if (!user) user = await User.create({ id: sender, name: msg.pushName });

                                                                                                                                                                                                                    // 2. PRIVATE MODE
                                                                                                                                                                                                                            if (config.workMode === 'private' && sender !== config.ownerNumber) return;

                                                                                                                                                                                                                                    // 3. AUTO-REPLY AD (Mention)
                                                                                                                                                                                                                                            const botId = jidDecode(sock.user.id).user + '@s.whatsapp.net';
                                                                                                                                                                                                                                                    if (text.includes('@' + botId.split('@')[0])) {
                                                                                                                                                                                                                                                                 await sock.sendMessage(sender, {
                                                                                                                                                                                                                                                                                 text: `Hello @${sender.split('@')[0]}!`,
                                                                                                                                                                                                                                                                                                 mentions: [sender],
                                                                                                                                                                                                                                                                                                                 contextInfo: {
                                                                                                                                                                                                                                                                                                                                     externalAdReply: {
                                                                                                                                                                                                                                                                                                                                                             title: config.adName,
                                                                                                                                                                                                                                                                                                                                                                                     body: config.adSlogan,
                                                                                                                                                                                                                                                                                                                                                                                                             thumbnailUrl: "https://i.imgur.com/P5yUpuM.png",
                                                                                                                                                                                                                                                                                                                                                                                                                                     sourceUrl: config.adLink,
                                                                                                                                                                                                                                                                                                                                                                                                                                                             mediaType: 1,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     renderLargerThumbnail: true
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     }, { quoted: msg });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     // 4. COMMAND HANDLER
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             if (text.startsWith(config.prefix)) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         const args = text.slice(config.prefix.length).trim().split(/ +/);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     const cmd = args.shift().toLowerCase();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 const isCreator = sender === config.ownerNumber;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             const isSudo = user.role === 'sudo' || isCreator;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         // --- COMMANDS ---

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     if (cmd === 'ping') {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     await sock.sendMessage(sender, { text: 'Pong! ⚡' });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             if (cmd === 'wallet') {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             await sock.sendMessage(sender, { text: `💰 Wallet: $${user.wallet}` });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     if (cmd === 'addsudo' && isCreator) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     const target = args[0] + '@s.whatsapp.net';
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     await User.updateOne({ id: target }, { role: 'sudo' });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     await sock.sendMessage(sender, { text: '✅ Sudo Added' });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         if (cmd === 'mode' && isCreator) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         config.workMode = args[0];
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         await sock.sendMessage(sender, { text: `Mode set to: ${args[0]}` });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 startBot();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 